##############################
#
# Fit a linear model for n (n>2) saturation mutagenesis replicates.
#
# The script uses the variant matrix generated by extractVariantMatrix.py or extractVariantMatrixHandleIndels.py 
# for each replicate and the name of the replicate.
# The output are the model coefficients for each variant.
#
# Usage:
# Rscript fitModelCombined.R <output> <vaiantMatrix_1> <variantMatrix_2> ... <variantMatrix_n> <name_rep1> <name_rep2> ... <name_repn>
# 
# Example:
# Rscript fitModelCombined.R Condition1.Combined.VarMatrix1bpDel.ModelCoefficients.txt Condition1.rep1.VarMatrix1bpDel.tsv.gz Condition1.rep2.VarMatrix1bpDel.tsv.gz Condition1.rep3.VarMatrix1bpDel.tsv.gz rep1 rep2 rep3
# 
# Authors:
# Max Schubach <max.schubach@bihealth.de>
#
##############################


library(dplyr)

args <- commandArgs(trailingOnly = TRUE)

replicates=((length(args)-1)/2)
l <- c(0)
reps <- c()
for (i in 2:(length(args)-replicates)){

  rep=args[i+replicates]
  reps <- c(reps,rep)

  file=args[i]
  print(file)
  print(rep)
  input <- read.table(file,as.is=T,header=T,sep="\t",comment.char="~")
  if (i == 2){
    data <- input
  } else {
    input <- input[,colnames(input) %in% colnames(data)]
    data <- data[,colnames(data) %in% colnames(input)]
    data <- rbind(data,input)
  }
  l <- c(l,dim(data)[1])
}

# Create indicator variables
for (i in 1:length(reps)) {
  name <- paste0("isRep",reps[i])
  data[[name]] <- 0
  start <- l[i]+1
  end <- l[i+1]

  data[[name]][start:end] <- 1
}

linComb = ""
for (i in 1:length(reps)) {
  name <- paste0("isRep",reps[i])
  data[[name]] <- data[[name]]*log2(data$DNA)
  if (i == 1) {
    linComb <- name
  } else {
    linComb = paste(linComb, name, sep=" + ")
  }
}

print("Start glm")
model <- glm(as.formula(sprintf("log2(RNA) ~ %s + %s", linComb, paste(colnames(data)[4:(dim(data)[2]-3)],collapse=" + "))), data=data)
model$data <- NULL
write.table(summary(model)$coefficients, file=args[1], row.names=T, col.names=F, quote=F, sep="\t")
